# Training Configs
training_cfg:
  max_epochs: 50
  batch_size: 128
  seed: 2333
  resume_run_id: null
  resume_ckpt_type: null

# Optimizer Configs
optimizer_cfg:
  lr: 0.001
  lr_hlc: 0.0005
  lr_scheduler:
    milestones: [30, 40]
    gamma: 0.5

# Model Configs
model_cfg:
  model_name: "pengwu_net"
  dropout_prob: 0.6
  hlc_ctx_len: 1
  threshold: 0.7
  sigma: 1.0
  gamma: 1.0
  loss:
    lambda: 5.0
    is_topk: true
    q: 16

# Dataset Configs
dataset_cfg:
  feature_name: "i3d_rgb"
  seperated_by_class: false
  feature_dim: 2048
  clip_len: 32
  sampling_rate: 2
  streaming: false
  max_seq_len: 200
  num_workers: 4

# Logging Configs
logging_cfg:
  exp_name: hlnet-ctx_len_1-i3d
  log_interval_steps: 10
  ckpt_interval_epochs: 2
  test_interval_epochs: 2
  log_dir: "./logs/"
  test_metric: "ap_offline"
